### ISSUE TITLE
Error: Cannot find module (after upgrading from 15.9.0 to 15.10.1)

### ISSUE THREAD

**Issue by honzajavorek** [stylelint/stylelint#7057]
### What minimal example or steps are needed to reproduce the bug?

1. Have a working stylelint configuration, e.g. as in https://github.com/honzajavorek/junior.guru/
2. Have a dependabot suggest an upgrade to the latest version https://github.com/honzajavorek/junior.guru/pull/1187
3. See CI failed with the following error:

```
Error: Cannot find module 'stylelint/lib/utils/isRangeContextMediaFeature'
Require stack:
- /home/circleci/project/node_modules/stylelint-stylistic/dist/rules/media-feature-name-case/index.js
- /home/circleci/project/node_modules/stylelint-stylistic/dist/main.js
- /home/circleci/project/node_modules/stylelint/lib/augmentConfig.js
- /home/circleci/project/node_modules/stylelint/lib/createStylelint.js
- /home/circleci/project/node_modules/stylelint/lib/resolveConfig.js
- /home/circleci/project/node_modules/stylelint/lib/printConfig.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/circleci/project/node_modules/stylelint-stylistic/dist/rules/media-feature-name-case/index.js:5:36)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
Aborted!
```

I tried to dig into the root cause, but honestly, I'm completely lost and confused about what could be the culprit. The only thing I know is that v15.9.0 works fine.

### What minimal configuration is needed to reproduce the bug?

```json
{
  "extends": "stylelint-config-twbs-bootstrap"
}
```

### How did you run Stylelint?

```python
subprocess.run(['npx', 'stylelint',
                'juniorguru/scss/**/*.*css',
                'juniorguru/image_templates/*.*css'], check=True)
```

### Which Stylelint-related dependencies are you using?

```json
{
  "stylelint": "15.9.0",
  "stylelint-config-twbs-bootstrap": "11.0.0"
}
```

### What did you expect to happen?

To lint, as with v15.9.0.

### What actually happened?

Stylelint crashes with a cryptic error.

### Do you have a proposal to fix the bug?

If the issue is out of scope of Stylelint, at least the error could point me to the right places.

**Comment by TyIsI** [comment]
Random other person who ran into this issue reporting in.

After searching for about an hour, I found it was removed in commit 
[8051822e502f75f62b812ad6cb83f613dbd5d843](https://github.com/stylelint/stylelint/commit/8051822e502f75f62b812ad6cb83f613dbd5d843).

The root cause is in the `stylelint-stylistic` package.

Retiring the isRangeContextMediaFeature functionality would be expected to be mentioned as breaking functionality. So maybe a little learning moment for the stylelint team.

Off I go to report this to the `stylelint-stylistic` maintainer!

**Comment by romainmenke** [comment]
Hi all, 

I submitted the pull request that introduced this issue 👋 
The function that was removed was an [internal utility](https://github.com/stylelint/stylelint/blob/main/docs/developer-guide/plugins.md#stylelintutils) that, to the best of my knowledge, wasn't used by other packages. From my perspective this wasn't a breaking change.

Obviously this turned out to be incorrect.

--------

Speaking strictly for myself and not representing anyone in this section :

I do want to say that this is not a learning moment for me.

I know that it can be annoying and frustrating when a tool you depend on suddenly throws errors.

Sometimes you just make a change that you think will be good for everyone and you get it wrong. This happens and this is fine.

--------

The package using this function is intended as a replacement for deprecated rules.
So I am inclined to restore the utility, even if this utility isn't used internally any more.

Even more so because this package hasn't seen any activity in the last 2 months.
So I think restoring the utility is the quickest way to help affected users.

The utility can be removed again in `v16`.

**Comment by honzajavorek** [comment]
I totally understand things can break, even if one thinks they shouldn’t.
By the way, thanks for all the awesome work!

I’m all for changes and deprecations, if they have a clear path forward.
I’m not educated about the project enough to decide if reverting is the
best thing to do, or if documenting a workaround or else is better.

I use Bootstrap’s config, because I use Boostrap and I want to keep my
(S)CSS aligned. As Bootstrap is rather popular project, I guess this might
affect more people.

When looking for the possible root cause of my problem, I’ve bumped into
this
https://github.com/twbs/stylelint-config-twbs-bootstrap/issues/206, which I
didn’t know could be related, but reading the comments here it seems it
might be 🤔

**Comment by ybiquitous** [comment]
We've recently updated our document about the utilities with PR #7052:

https://github.com/stylelint/stylelint/blob/cefd26769a9995d0e7484cd9f0d0bab83e7dc8d4/docs/developer-guide/plugins.md?plain=1#L216-L220

As possible, we don't want people to use internal utilities. Instead, we want them to use `stylelint.utils` since it's a public API.

We've been performing many refactorings, such as removing unused utilities and dependencies, to keep this project healthy. Restoring removed and unused them would worsen the project's maintainability. It'd become hard to determine whether we could remove such components.

Fortunately, <https://github.com/elirasza/stylelint-stylistic/issues/12> seems to be working. I'd like to wait for the new release of `stylelint-stylistic` if possible.

**Comment by honzajavorek** [comment]
https://github.com/elirasza/stylelint-stylistic/issues/12 is now resolved and new version released! The following has helped me to get a working stylelint installation:

```
npm uninstall stylelint-config-twbs-bootstrap 
npm install --dev stylelint-config-twbs-bootstrap
```

This upgrades stylelint-stylistic's version from 0.4.2 to 0.4.3 in the package-lock.json. Thanks everyone involved.
