### ISSUE TITLE
Fix "TypeError: opts.node.rangeBy is not a function" with PostCSS 8.4.4

### ISSUE THREAD

**Issue by fomenkogregory** [stylelint/stylelint#5766]
### What steps are needed to reproduce the bug?

folder structure:
  package.json
  .stylelintrc.json
  styles.scss (empty file)

 package.json:
```js
{
  "name": "untitled2",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "lint": "npx stylelint '**/*.scss'"
  },
  "devDependencies": {
    "stylelint": "^14.1.0",
    "stylelint-config-standard-scss": "^3.0.0"
  }
}
```

**npm i**
**npm run lint**

### What Stylelint configuration is needed to reproduce the bug?

```js
{
  "extends": "stylelint-config-standard-scss"
}
```

### How did you run Stylelint?

npx stylelint '**/*.scss'

### Which version of Stylelint are you using?

^14.1.0

### What did you expect to happen?

I expect stylelint to show list of errors.

### What actually happened?

```
TypeError: opts.node.rangeBy is not a function
at new Warning (node_modules/postcss/lib/warning.js:9:29)
at Result.warn (node_modules/postcss/lib/result.js:26:19)
at report (node_modules/stylelint/lib/utils/report.js:103:9)
at node_modules/stylelint/lib/rules/no-empty-source/index.js:28:3
at node_modules/stylelint/lib/lintPostcssResult.js:112:8
at Array.map (<anonymous>)
at lintPostcssResult (node_modules/stylelint/lib/lintPostcssResult.js:103:18)
at lintSource (node_modules/stylelint/lib/lintSource.js:88:8)
at async node_modules/stylelint/lib/standalone.js:218:27
at async Promise.all (index 0)

Process finished with exit code 1
```

The problem is in this line

![image](https://user-images.githubusercontent.com/51916577/145043105-9953bd0c-48e0-4a9e-92c1-6784998c7852.png)

### Does the bug relate to non-standard syntax?

No

### Proposal to fix the bug

Works correctly with exactly 8.3.11 version of postcss. 
I compared the code in `warning.js` between these versions of postcss (8.3.11 and 8.4.4), they changed the method name. :(

Proposal: change dependencies of stylelint to use exactly 8.3.11 version.

**Comment by ai** [comment]
Could it happen because of the different PostCSS versions at chimera’s AST containing nodes from different PostCSS versions?

Can you look `npm ls` for different PostCSS versions?

**Comment by vankop** [comment]
> Can you look npm ls for different PostCSS versions? 

In our case we have a problem using https://github.com/ismay/stylelint-no-unsupported-browser-features/blob/master/package.json this package has postcss as a dependency

**Comment by fomenkogregory** [comment]
this is npm ls from this example

└─┬ stylelint@14.0.1
  └── postcss@8.4.4

**Comment by fomenkogregory** [comment]
and this is from another projects (new angular 13 project) (works fine)

└─┬ stylelint@14.0.1
  ├─┬ postcss-safe-parser@6.0.0
  │ └── postcss@8.3.6 deduped
  └── postcss@8.3.11

**Comment by p-m-p** [comment]
I'm also seeing this on the `no-empty-source` rule, same versions as @fomenkogregory installed today.

**Comment by ybiquitous** [comment]
I've created a reproduction repository, but such a `TypeError` never occurs. 🤔 
Is there something I missed?

https://github.com/ybiquitous/stylelint-issue-5766/runs/4451335382?check_suite_focus=true#step:5:13

<img width="521" alt="image" src="https://user-images.githubusercontent.com/473530/145128696-008247e1-e0c3-4402-8a38-f959383b27f1.png">

**Comment by ai** [comment]
@fomenkogregory can you try to update dependencies by running `npm update` or `yarn upgrade` to test that it is happens because of different PostCSS versions?

**Comment by fomenkogregory** [comment]
> I've created a reproduction repository, but such a `TypeError` never occurs. 🤔 Is there something I missed?
> 
> https://github.com/ybiquitous/stylelint-issue-5766/runs/4451383596?check_suite_focus=true#step:6:1
> 
> <img alt="image" width="521" src="https://user-images.githubusercontent.com/473530/145128696-008247e1-e0c3-4402-8a38-f959383b27f1.png">

thanks! I'll try to clone your repo and see if it will work on my side. Than I will compare lock file and node_modules and will see what's differs.

**Comment by lregla** [comment]
Also started with a fresh install of `stylelint@14.1.0` and `stylelint-config-standard-scss@3.0.0`. Ran into the same error described above. Installed `postcss@8.4.4` as @BroFox86 did, and the error is gone.

**Comment by ai** [comment]
Thanks for the help.

I will try to find solution during this weekend.

**Comment by fomenkogregory** [comment]
> Also started with a fresh install of `stylelint@14.1.0` and `stylelint-config-standard-scss@3.0.0`. Ran into the same error described above. Installed `postcss@8.4.4` as @BroFox86 did, and the error is gone.

And moreover, you can then uninstall postcss and all works fine for current and all future projects. I wasn't able to reproduce the issue for any new projects as well.

**Comment by RiZKiT** [comment]
Seems to be related to/a duplicate of: https://github.com/stylelint/stylelint/issues/5756

**Comment by Yohandah** [comment]
When will it ship ?

**Comment by ai** [comment]
@Yohandah the solution was not found. Please help in investigation and send PR if you want to fix it sooner.

**Comment by Yohandah** [comment]
Sorry I read too fast I thought a PR was ready.

A weird thing happened while I was looking for a fix.

I removed `"stylelint-config-prettier"` from my extends array, the error was gone, then I re-added it to see if the errors comes back, and it's completely gone I can't reproduce it.

**Comment by ijcnvv** [comment]
totally uninstalling postcss & stylelint with their plugins helped me. I Installed postcss at first and then stylelint and have no errors now

**Comment by Yohandah** [comment]
It seems the error only happens when I comment using // instead of /* ?

https://user-images.githubusercontent.com/15921402/152132550-6c588314-bff4-499f-910a-2c579860647b.mp4

**Comment by KeithGillette** [comment]
Installing `postcss@latest` (`8.4.6` at my testing) then uninstalling it prevented the `TypeError: opts.node.rangeBy is not a function` error upon updating to `stylelint@14.2.0` in our project, just as @fomenkogregory found. 🤷🏻‍♂️

**Comment by ThomasHenrissat** [comment]
> It seems the error only happens when I comment using // instead of /* ?

I can confirm this. When I removed the `//` comments from my file the error stopped showing up.

**Comment by HarwinBorger** [comment]
> It seems the error only happens when I comment using // instead of /* ?
> Screenshare.-.2022-02-02.10_57_16.AM.mp4

While this seems to cause the problem, i figured out that (for e) it actually is caused by just empty spaces (such as indenting). I tried `  ` (double empty space) and it caused the error also. 

This can be reproduced by searching for an empty line, and add a couple of spaces on that empty line.

**Comment by timotgl** [comment]
I could reproduce this with a completely empty file (0 bytes, no characters). Adding even an empty comment with `//` fixed it in my case.

macOS 12.2.1
Node.js v16.13.2
npm 8.1.2
stylelint@14.5.1

**Comment by guoyucloud** [comment]
将postcss降级到8.3.11这个版本是可以暂时缓解该问题的。
`"postcss": "8.3.11",`

**Comment by scherii** [comment]
English translation of the above:
«Downgrading postcss to version 8.3.11 can temporarily alleviate the problem.»

**Comment by artforlife** [comment]
> Also started with a fresh install of `stylelint@14.1.0` and `stylelint-config-standard-scss@3.0.0`. Ran into the same error described above. Installed `postcss@8.4.4` as @BroFox86 did, and the error is gone.

Using these versions seems to have fixed it for me. Thanks!

**Comment by Maleficentt** [comment]
> 将postcss降级到8.3.11这个版本是可以暂时缓解该问题的。 `"postcss": "8.3.11",`

为什么我的不行

**Comment by snebjorn** [comment]
I have a guess as to what is going on.

So the problem is that the function `rangeBy` isn't defined. It's being called here
https://github.com/stylelint/stylelint/blob/main/lib/utils/report.js#L17
```ts
/** @type {typeof import('stylelint').utils.report} */
module.exports = function report(problem) {
	const { ruleName, result, message, line, node, index, endIndex, word } = problem;

	// omitted

	const { start } = (node && node.rangeBy({ index, endIndex })) || {};
	//                              ^ -- issue is here
```
And it looks like the `problem` parameter is coming from a callback that plugins are responsible for.

I got to that conclusion because `createPlugin` is setting up the callback.
https://github.com/stylelint/stylelint/blob/main/types/stylelint/index.d.ts#L443
```ts
createPlugin: (ruleName: string, plugin: Plugin) => { ruleName: string; rule: Rule };
```

When you dive into the `Plugin` type you go to this bit which defines this callback `(root: PostCSS.Root, result: PostcssResult)`
https://github.com/stylelint/stylelint/blob/main/types/stylelint/index.d.ts#L176
```ts
export type RuleBase<P = any, S = any> = (
  primaryOption: P,
  secondaryOptions: Record<string, S>,
  context: PluginContext,
) => (root: PostCSS.Root, result: PostcssResult) => Promise<void> | void;
```

Now... `rangeBy` was added in PostCSS@8.4.0 https://github.com/postcss/postcss/blob/8.4.0/lib/node.d.ts#L477 and plugins are responsible for executing the `(root: PostCSS.Root, result: PostcssResult)` callback. So if the plugin in question isn't using PostCSS@8.4.0 or greater then the `rangeBy` function won't be defined in the `report` function called by Stylelint.

I can backup this thesis with an example.
I've setup my Stylelint with the plugin `stylelint-prettier@2.0.0` and I'm getting `node.rangeBy is not a function`.
`stylelint-prettier@2.0.0` have this dependency `postcss": "^8.3.11"`
https://github.com/prettier/stylelint-prettier/blob/main/package.json#L46
Now that's a range, so lets check the lock file https://github.com/prettier/stylelint-prettier/blob/main/yarn.lock#L3009 and there we see it's only `version "8.3.11"`

I believe that every stylelint plugin needs to update their PostCSS dependency to at least 8.4.0 to be compatible with `Stylelint@14.7.0`.
`Stylelint@14.7.0` is the version that introduced the `node.rangeBy` call.

How to best solve this dependency issue, I'll leave to the experts 😃

**Comment by ybiquitous** [comment]
@snebjorn Thanks for the detailed comment. Yes, this error is due to using the outdated PostCSS version.

Since Stylelint 14.7.0 requires PostCSS 8.4.12 as below, I think this error never happens if there are no problems in dependency resolutions:

https://github.com/stylelint/stylelint/blob/91c36013d5b904471f2f32adb307431e13d283c6/package.json#L136

I recommend re-checking project dependencies and installing that dependencies cleanly as possible.

**Comment by ybiquitous** [comment]
I believe the simplest way to resolve the error is to install the latest versions of Stylelint and PostCSS.

I'm not sure if Stylelint should do something to address this problem. I wish anyone would provide a minimal reproduction repository to make investigation easier (for some package managers if possible)... 😓

**Comment by snebjorn** [comment]
I think I have part of the answer. 

Stylelint it self have a dependency on 


I have a project where I updated stylelint from an older version.

**Comment by snebjorn** [comment]
I think I have part of the answer.

Stylelint it self have a dependency on `@csstools/selector-specificity`

https://github.com/stylelint/stylelint/blob/0d2c6cd98192b48d2cd5c8b305154aadd63a8a22/package.json#L111

`@csstools/selector-specificity` have a dependency on `postcss@^8.2`

https://github.com/csstools/postcss-plugins/blob/cb7490ed905947e6877fa7261dce8990ea24166f/packages/selector-specificity/package.json#L41

I have a project where I updated stylelint from an older version. The postcss version that satisficed ^8.2 when I first installed stylelint was `postcss@8.3.6`. When I when to update stylelint to 14.9.1 then my installed `postcss@8.3.6` still satisficed `postcss@^8.2` and thus I end up with this dependency graph

```
└─┬ stylelint@14.9.1
  ├─┬ @csstools/selector-specificity@2.0.2
  │ └── postcss@8.3.6 deduped    <------------ NOTICE
  ├─┬ postcss-safe-parser@6.0.0
  │ └── postcss@8.3.6 deduped    <------------ NOTICE
  └── postcss@8.4.14
```
So in my local install when a rule using @csstools/selector-specificity would trigger I'd end up with `node.rangeBy is not a function` because `@csstools/selector-specificity@2.0.2` is using `postcss@8.3.6` internally.

I'm still working on a minimal reproducible repo. But with the above dependency graph I got this error from a built-in stylelint rule

```
TypeError: node.rangeBy is not a function
    at report (~\myproject\node_modules\stylelint\lib\utils\report.js:31:34)
    at reportFromIndex (~\myproject\node_modules\stylelint\lib\rules\no-eol-whitespace\index.js:105:4)
    at ~\myproject\node_modules\stylelint\lib\rules\no-eol-whitespace\index.js:146:7
    at handleMatch (~\myproject\node_modules\style-search\index.js:201:5)
    at module.exports (~\myproject\node_modules\style-search\index.js:189:5)
    at eachEolWhitespace (~\myproject\node_modules\stylelint\lib\rules\no-eol-whitespace\index.js:133:4)
    at ~\myproject\node_modules\stylelint\lib\rules\no-eol-whitespace\index.js:114:3
    at ~\myproject\node_modules\stylelint\lib\lintPostcssResult.js:113:8
    at Array.map (<anonymous>)
    at lintPostcssResult (~\myproject\node_modules\stylelint\lib\lintPostcssResult.js:104:18)
```
This basically means that somewhere a `node` was created using `postcss@8.3.6`.

**Comment by ybiquitous** [comment]
@snebjorn Thanks for your time! It doesn’t seem that just updating Stylelint always leads to updating PostCSS together. It may be necessary to update PostCSS via an extra command like [`npm update`](https://docs.npmjs.com/cli/v8/commands/npm-update).

Anyway, I look forward to your subsequent investigation.

**Comment by snebjorn** [comment]
I found it! 
The issue is with the custom syntax parsers. Here Stylelint is handing over control to PostCSS and it's using the correct 8.4.14 version. The parser in this case is `postcss-less`.

![image](https://user-images.githubusercontent.com/1266245/182040319-e119bec8-1f36-44b3-9f45-8db8cdfdac20.png)
https://github.com/stylelint/stylelint/blob/9edf55135742be55fda8fac07566edf9c16241ba/lib/getPostcssResult.js#L77

Inside LazyResult we end up here. At this point we're still using the nested PostCSS bundled with Stylelint. (This is good)
```js
// omitted
} else {
  let parser = parse
  if (opts.syntax) parser = opts.syntax.parse
  if (opts.parser) parser = opts.parser
  if (parser.parse) parser = parser.parse

  try {
  root = parser(css, opts)    // here PostCSS hands off control to the parser `postcss-less`
  } catch (error) {
  // omitted
```
source: https://github.com/postcss/postcss/blob/e731697dffd2e14da609503a5114d3a28c948334/lib/lazy-result.js#L133

So far so good. But now it starts to go wrong. Because `postcss-less` import PostCSS.
```js
const Input = require('postcss/lib/input'); // <--- imports PostCSS outside the scope of Stylelint

const LessParser = require('./LessParser');
const LessStringifier = require('./LessStringifier');

module.exports = {
  parse(less, options) {
```
source: https://github.com/shellscape/postcss-less/blob/master/lib/index.js#L3

But we're no longer in the scope of Styellint.
Looking at the stack track makes it very clear that we're no longer "inside" stylelint

![image](https://user-images.githubusercontent.com/1266245/182041236-49214823-6cff-4e1f-9660-79278010e489.png)

`postcss-less` have correctly declared PostCSS as a peer dependency
```json
  "peerDependencies": {
    "postcss": "^8.3.5"
  },
```
source: https://github.com/shellscape/postcss-less/blob/984f4901aced4b74535d96b04242681d538d628b/package.json#L50

In my case, because I updated packages, I have this dependency graph
```
┬ postcss-less@6.0.0
└── postcss@8.3.6 deduped
```

**A solution?**
I think the correct fix for this is to have Stylelint declare PostCSS as a peer dependency.
That way Stylelint can increase the version of PostCSS and plugins that correctly list PostCSS as a peer dependency (with a range that compatible with Stylelint) will follow along.

**Comment by JounQin** [comment]
> I think the correct fix for this is to have Stylelint declare PostCSS as a peer dependency.

Thanks for your efforts first.

But I don't think it's acceptable for stylelint.

In details, stylelint is a singleton cli tool without any peer dependencies, changing postcss as peer would be a breaking change and changes a lot for end users.

**Comment by ai** [comment]
@snebjorn thanks for very deep invastigation.

We have a special tool to normalize AST in PostCSS https://github.com/postcss/postcss/blob/main/lib/container.js#L318-L331

Why is it not helped here?

**Comment by ai** [comment]
I created an issue to update PostCSS in `postcss-less` as a quick fix

**Comment by snebjorn** [comment]
Now that I understand the issue I was able to make a repo to reproduce the error.
As requested here's the error showing up using [NPM](https://github.com/snebjorn/styelint-no-rangeBy/tree/npm) and here for [Yarn](https://github.com/snebjorn/styelint-no-rangeBy/tree/yarn)

> stylelint is a singleton cli tool without any peer dependencies, changing postcss as peer would be a breaking change and changes a lot for end users.

That's unfortunate. Though NPM will automatically install peer dependencies since NPM v7. So it should have little impact.
However the same cannot be said for Yarn as it does not do that.

It's troublesome they don't behave in a similar fashion. Let's hope they come to a consensus on how to deal with dependencies. But that'll probably take years.

**Comment by ybiquitous** [comment]
@snebjorn Thank you so much for taking the time for this problem investigation! 😊 

Based on your investigation and reproduction repository, I could create PR #6241, but I'm not confident whether the PR is a good solution.

I believe the best solution is to use only one version of PostCSS and keep PostCSS up-to-date in a dependency tree for now.

**Comment by JounQin** [comment]
@ybiquitous Or can we add a warning for users instead on `postcss`'s side?

And as @ai said at https://github.com/stylelint/stylelint/issues/5766#issuecomment-1200504530

It may still need investigation actually, the current hack is the not propose solution IMO.

**Comment by ybiquitous** [comment]
@JounQin Thanks for the comment. To be honest, I don't know how to apply the way on <https://github.com/stylelint/stylelint/issues/5766#issuecomment-1200504530>... 😓

If PostCSS would provide a more elegant solution, I'm glad to adopt it.

**Comment by JounQin** [comment]
> @JounQin Thanks for the comment. To be honest, I don't know how to apply the way on [#5766 (comment)](https://github.com/stylelint/stylelint/issues/5766#issuecomment-1200504530)... 😓
> 
> If PostCSS would provide a more elegant solution, I'm glad to adopt it.

Me too. 😅

@ai Can you help to explain how's your commented codes related to `node.rangeBy`?

**Comment by ai** [comment]
> Or can we add a warning for users instead on postcss's side?

Of course, but I am not sure where and what I should check before showing the warning

**Comment by ybiquitous** [comment]
@ai Stylelint uses [`LazyResult`](https://postcss.org/api/#lazyresult) to get parsing results. For example, when a user specifies `customSyntax: 'postcss-less'`, the `postcss-less` syntax object is passed to `new LazyResult()`. See below:

https://github.com/stylelint/stylelint/blob/e424be5eca77c5532b13147c4a7dad14085a4276/lib/getPostcssResult.js#L40-L47

https://github.com/stylelint/stylelint/blob/e424be5eca77c5532b13147c4a7dad14085a4276/lib/getPostcssResult.js#L77

Given the following dependency tree (see the [snebjorn/styelint-no-rangeBy](https://github.com/snebjorn/styelint-no-rangeBy) repo),

```
/
├─┬ postcss-less@6.0.0
│ └── postcss@8.3.5 deduped
├── postcss@8.3.5
└─┬ stylelint@14.9.1
  ├─┬ @csstools/selector-specificity@2.0.2
  │ └── postcss@8.3.5 deduped
  ├─┬ postcss-safe-parser@6.0.0
  │ └── postcss@8.3.5 deduped
  └── postcss@8.4.14
```

Then, `LazyResult` returns a result object including nodes produced by `postcss@8.3.5` (`postcss-less@6.0.0`), while `stylelint@14.9.1` tries to handle them as a node compatible with `postcss@8.4.14` that has the `rangeBy()` method. However, since actual nodes don't have `rangeBy()`, `TypeError` raises:

https://github.com/stylelint/stylelint/blob/e424be5eca77c5532b13147c4a7dad14085a4276/lib/utils/report.js#L31

We're looking for how to absorb node differences between PostCSS versions.

**Comment by JounQin** [comment]
@ybiquitous So the key problem is `postcss@8.3.5` which is called later does not have `node.rangeBy` right? Then it seems to be a breaking change between patches of versions from `postcss`?

**Comment by ybiquitous** [comment]
> So the key problem is `postcss@8.3.5` which is called later does not have `node.rangeBy` right? Then it seems to be a new feature between minor versions from `postcss`?

@JounQin Yes, right. The `rangeBy` method has been added with PostCSS 8.4.0. See the changelog:

> - Added ranges for errors and warnings (by Adaline Valentina Simonian).

https://github.com/postcss/postcss/blob/main/CHANGELOG.md#84-president-camio

**Comment by snebjorn** [comment]
I think monkey patching is a dangerous path to take. When looking through the code of Stylelint it's not obvious that a different PostCSS version might be used at runtime. It's just a matter of time before the next thing needs to be monkey patched, and so on.

If PostCSS can somehow guarantee that the `postcssProcessor` passed to it is the version used then all is well. Though I think that'll be a tough one to crack. Though I haven't given it much thought.

I must mention the Peer Dependency solution again as it fixes everything.
I did a simple test where I wrapped Stylelint in a package with these peerDependencies
```json
"peerDependencies": {
  "postcss": "^8.4.14",
  "stylelint": ">=14"
},
```
Using NPM v8.16.0 I installed my wrapper package `npm i -D wrapped-stylelint` and I ended up with this dependency graph
```
│ ├─┬ postcss-less@6.0.0
│ │ └── postcss@8.4.14 deduped
│ ├── postcss@8.4.14
└─┬ stylelint@14.9.1
  ├─┬ @csstools/selector-specificity@2.0.2
  │ └── postcss@8.4.14 deduped
  ├─┬ postcss-safe-parser@6.0.0
  │ └── postcss@8.4.14 deduped
  └── postcss@8.4.14 deduped
```
Note I didn't install PostCSS. I just installed `wrapped-stylelint`.
So the impact of this breaking change is minimal for NPM users since v7 (I didn't actually test NPM v7)

The only bad thing about this solution is Yarn users will have to manually install PostCSS.
But perhaps some traffic here https://github.com/yarnpkg/yarn/issues/1503 could change that

**Comment by JounQin** [comment]
> It's just a matter of time before the next thing needs to be monkey patched, and so on.

I agree with this part. But it seems we only have this issue for `node.rangeBy` and we do rely on this prototype method to work correctly. Another solution would be that we just copy the `rangeBy` method into `stylelint`, but this has the same situation as you said.

> I must mention the Peer Dependency solution again as it fixes everything.

You know that it is not acceptable for `yarn` or `pnpm` or `npm < 7`.

**Comment by ai** [comment]
I have an idea, give me a weekend.

Here is a plan:

1. Patch `postcss-less` to use PostCSS 8.4
2. Add extra check for different AST version from parser to PostCSS core

**Comment by JounQin** [comment]
> Here is a plan:

This will not work when a user has installed a older version of `postcss` which is the key issue here.

**Comment by ai** [comment]
> This will not work when a user has installed a older version of postcss which is the key issue here.

Yes, at least user will need fresh PostCSS version.

Good part: in a few month most of users will update their dependencies.

Or at least, we can ask them to update `postcss` by smoe npm tools.

**Comment by JounQin** [comment]
@ai 

postcss is a peer dependency from `postcss-less`, so upgrading `postcss` in `postcss-less` does not help.

By patching `postcss` in `stylelint`, the users only need to upgrade `stylelint`.

I think we don't need to waste time on it. Patching is the best choice IMO.

**Comment by ai** [comment]
@JounQin hm, we already have a special code in PostCSS to rebuild AST if parser return old version

https://github.com/postcss/postcss/blob/main/lib/lazy-result.js#L139-L142

Can you check why it was not called in this case?

**Comment by JounQin** [comment]
@ai I'm not so familiar with the source codes from `postcss`, and I don't quite understand where `node.rangeBy` will be normalized back? Can you point it more specifically?

**Comment by ai** [comment]
@JounQin `Container.rebuild` replaces prototype of every nodes object of AST. So even if parse returned old AST, `rebuild` will update it to me version.

**Comment by JounQin** [comment]
It's still unclear where `node.rangeBy` would be patched by `Container.rebuild()` to me. 😅

**Comment by snebjorn** [comment]
@JounQin The assignment of the rangeBy function is done here https://github.com/postcss/postcss/blob/main/lib/container.js#L415-L423 via [Object.setPrototypeOf()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf)

However the node that is throwing the error is of type `root` which the function doesn't handle.
```js
  if (node.type === 'atrule') {
    Object.setPrototypeOf(node, AtRule.prototype)
  } else if (node.type === 'rule') {
    Object.setPrototypeOf(node, Rule.prototype)
  } else if (node.type === 'decl') {
    Object.setPrototypeOf(node, Declaration.prototype)
  } else if (node.type === 'comment') {
    Object.setPrototypeOf(node, Comment.prototype)
  }
```
The function is being called for the root type.
![image](https://user-images.githubusercontent.com/1266245/183257378-9eb6613c-e707-4915-931a-db60dc2f98b1.png)

@ai could that be the issue?

**Comment by ai** [comment]
@snebjorn exactly! I added the fix https://github.com/postcss/postcss/commit/f289e173b07bfb72265692662db94e5c49e5f583

I released a fix in PostCSS 8.4.15. Can we try it?

**Comment by snebjorn** [comment]
Not sure where `Container.registerRoot` is getting called from. But I'm getting `Root` as `undefined` when I update the postcss version inside stylelint.

```
TypeError: Cannot read properties of undefined (reading 'prototype')
    at Container.rebuild (~\styelint-no-rangeBy\node_modules\stylelint\node_modules\postcss\lib\container.js:428:38)
```

**Comment by ai** [comment]
@snebjorn sorry, can you try again with PostCSS 8.4.16?

It was a small typo and we have not tests for AST migration hack.

**Comment by snebjorn** [comment]
Gentlemen, we have a winner!

```
❯ npm run stylelint

> stylelint
> stylelint src/**/*.less


src/foo.less
 2:22  ✖  Unexpected whitespace at end of line  no-eol-whitespace
```

**Comment by ai** [comment]
Now let’s bump Stylelint with the latest PostCSS version and ask every user just to update `stylelint` in their `package.json`.

**Comment by snebjorn** [comment]
Thanks for the quick responses. It kept me motivated :)
It's been a pleasure!

**Comment by ybiquitous** [comment]
@snebjorn @JounQin @ai
I appreciate your work very much! 👏🏼

**Comment by DreamShaded** [comment]
hi! so users have to wait stylelint v14.9.2, yep?)

**Comment by JounQin** [comment]
@ismay No, only postcss needs to be upgraded.

**Comment by JounQin** [comment]
@ismay I mean it's not required to upgrade to v14, you only need to upgrade the postcss dep on your side.

**Comment by zengshine** [comment]
> Now let’s bump Stylelint with the latest PostCSS version and ask every user just to update `stylelint` in their `package.json`.
> 
> Thanks to @JounQin and @snebjorn for solving this very complex bug.

respect!

**Comment by AndyOGo** [comment]
I face that type error again after upgrading to `v15`

> TypeError: node.rangeBy is not a function
    at Object.report (/stylelint-declaration-strict-value/node_modules/stylelint/lib/utils/report.js:35:34)

**Comment by ybiquitous** [comment]
@AndyOGo That error should never occur if you are using the latest PostCSS. Please recheck your dependency tree.

**Comment by AndyOGo** [comment]
@ybiquitous 

Indeed, I'm surprised too.
```sh
npm ls postcss
└─┬ stylelint@15.0.0
  ├─┬ @csstools/selector-specificity@2.1.1
  │ └── postcss@8.4.21 deduped
  ├─┬ postcss-safe-parser@6.0.0
  │ └── postcss@8.4.21 deduped
  └── postcss@8.4.21
```
