### ISSUE TITLE
Don't work with svelte template more (v14)

### ISSUE THREAD

**Issue by shoonia** [stylelint/stylelint#5647]
The stylelint v13 work with Svelte template files (`*.svelte`).  New version v14 don't work with any Svelte files more.

Example:
```html
<script lang="ts">
  export let version: string;
</script>

<span>
  v{version}
</span>

<style>
  span {
    font-size: 12px;
    color: var(--d50);
  }
</style>
```

command:
```bash
npx stylelint 'src/**/*.svelte'
```

error:
```
src/components/ReleaseNote.svelte
 1:9  ✖  Unknown word  CssSyntaxError
```

npm
```
"stylelint": "^14.0.0",
"stylelint-config-standard": "^23.0.0",
```

`.stylelintrc`
```json
{
  "extends": [
    "stylelint-config-standard"
  ],
  "rules": {
    "selector-pseudo-class-no-unknown": [
      true,
      {
        "ignorePseudoClasses": [
          "global"
        ]
      }
    ]
  }
}
```

Do you have plan support Svelte template files?

**Comment by mantismamita** [comment]
Hello, I am havving a similar problem with `.svelte` files. I followed the above suggestion but am still getting an `Unknown rule CssSyntaxError` when a `<style>` tag is encountered. In the example below the error occurs on the line just below the style tag. Please let me know if it would be more helpful to create a seperate issue.

```
<script lang="ts">
  export { className as class };
  let className = '';
</script>

<span class="Label {className}"><slot /></span>

<style>
  .Label {
    border-radius: 5px;
    height: 22px;
    align-items: center;
    padding: 0 4px;
    text-transform: uppercase;
    pointer-events: none;
    background-color: var(--color-white);
  }
</style>
```

**Comment by ybiquitous** [comment]
@mantismamita Can https://github.com/stylelint/stylelint/issues/5685#issuecomment-957021031 help you?

**Comment by mantismamita** [comment]
I was just looking at `customSyntax: require('postcss-html')({ css: 'postcss-safe-parser' })` I'll see if that works. I have to out it into json format.

**Comment by ybiquitous** [comment]
Unforunately, the form like `require('postcss-html')(options)` is available only on JS configuration (e.g., `.stylelintrc.js`), not JSON. 😓

**Comment by mantismamita** [comment]
ah, that opens up another can of worms as vite (we're using Sveltekit) isn't fond of commonjs. I'll see if I can convert it to a .cjs and test it out.

**Comment by mantismamita** [comment]
Ok, I created at `stylelint.config.cjs` file like so : 

```
module.exports = { 
  extends: 'stylelint-config-standard',
  customSyntax: require('postcss-html')({ css: 'postcss-safe-parser' }),
}
```
bu am getting a 
`TypeError: opts.node.rangeBy is not a function`

any ideas?

**Comment by jeddy3** [comment]
> TypeError: opts.node.rangeBy is not a function

Possibly related to https://github.com/stylelint/stylelint/issues/5766

**Comment by mantismamita** [comment]
Ok, seems to be working with `postcss@8.4.4`

**Comment by jeddy3** [comment]
> However, I can't seem to pass the --fix flag without encountering heap memeory problems.

@mantismamita You don't seem to be having the best of luck. I don't think anyone has reported a heap memory problem before. Can you [open a new issue ](https://github.com/stylelint/stylelint/issues/new?assignees=&labels=&template=REPORT_A_BUG.yml)for that please, ideally with a reproducible example?

**Comment by mantismamita** [comment]
> @mantismamita You don't seem to be having the best of luck. I don't think anyone has reported a heap memory problem before. Can you open a new issue for that please, ideally with a reproducible example?

Heap memory problem seems to have been a once-off occurance. Cheers for letting me glom onto a an already closed issue. I'll open an issue if I can reproduce it.
