### PR TITLE
chore(deps): upgrade postcss to ^8.4.16

### LINKED ISSUE #5766: Fix "TypeError: opts.node.rangeBy is not a function" with PostCSS 8.4.4
### What steps are needed to reproduce the bug?

folder structure:
  package.json
  .stylelintrc.json
  styles.scss (empty file)

 package.json:
```js
{
  "name": "untitled2",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "lint": "npx stylelint '**/*.scss'"
  },
  "devDependencies": {
    "stylelint": "^14.1.0",
    "stylelint-config-standard-scss": "^3.0.0"
  }
}
```

**npm i**
**npm run lint**

### What Stylelint configuration is needed to reproduce the bug?

```js
{
  "extends": "stylelint-config-standard-scss"
}
```

### How did you run Stylelint?

npx stylelint '**/*.scss'

### Which version of Stylelint are you using?

^14.1.0

### What did you expect to happen?

I expect stylelint to show list of errors.

### What actually happened?

```
TypeError: opts.node.rangeBy is not a function
at new Warning (node_modules/postcss/lib/warning.js:9:29)
at Result.warn (node_modules/postcss/lib/result.js:26:19)
at report (node_modules/stylelint/lib/utils/report.js:103:9)
at node_modules/stylelint/lib/rules/no-empty-source/index.js:28:3
at node_modules/stylelint/lib/lintPostcssResult.js:112:8
at Array.map (<anonymous>)
at lintPostcssResult (node_modules/stylelint/lib/lintPostcssResult.js:103:18)
at lintSource (node_modules/stylelint/lib/lintSource.js:88:8)
at async node_modules/stylelint/lib/standalone.js:218:27
at async Promise.all (index 0)

Process finished with exit code 1
```

The problem is in this line

image

### Does the bug relate to non-standard syntax?

No

### Proposal to fix the bug

Works correctly with exactly 8.3.11 version of postcss. 
I compared the code in `warning.js` between these versions of postcss (8.3.11 and 8.4.4), they changed the method name. :(

Proposal: change dependencies of stylelint to use exactly 8.3.11 version.

### PR DESCRIPTION
**Pull request by JounQin**
> Which issue, if any, is this issue related to?

Closes #5766
Closes #6241

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

### CODE REVIEW

**Comment by JounQin** [comment]
I didn't add a test case for it because I don't know how to do it easily, and the issue should belong to `postcss` instead.

**Review by ybiquitous — APPROVED** [review]
@JounQin Thank you. LGTM!
