### PR TITLE
Restore `Node#rangeBy` method if not present

### LINKED ISSUE #5766: Fix "TypeError: opts.node.rangeBy is not a function" with PostCSS 8.4.4
### What steps are needed to reproduce the bug?

folder structure:
  package.json
  .stylelintrc.json
  styles.scss (empty file)

 package.json:
```js
{
  "name": "untitled2",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "lint": "npx stylelint '**/*.scss'"
  },
  "devDependencies": {
    "stylelint": "^14.1.0",
    "stylelint-config-standard-scss": "^3.0.0"
  }
}
```

**npm i**
**npm run lint**

### What Stylelint configuration is needed to reproduce the bug?

```js
{
  "extends": "stylelint-config-standard-scss"
}
```

### How did you run Stylelint?

npx stylelint '**/*.scss'

### Which version of Stylelint are you using?

^14.1.0

### What did you expect to happen?

I expect stylelint to show list of errors.

### What actually happened?

```
TypeError: opts.node.rangeBy is not a function
at new Warning (node_modules/postcss/lib/warning.js:9:29)
at Result.warn (node_modules/postcss/lib/result.js:26:19)
at report (node_modules/stylelint/lib/utils/report.js:103:9)
at node_modules/stylelint/lib/rules/no-empty-source/index.js:28:3
at node_modules/stylelint/lib/lintPostcssResult.js:112:8
at Array.map (<anonymous>)
at lintPostcssResult (node_modules/stylelint/lib/lintPostcssResult.js:103:18)
at lintSource (node_modules/stylelint/lib/lintSource.js:88:8)
at async node_modules/stylelint/lib/standalone.js:218:27
at async Promise.all (index 0)

Process finished with exit code 1
```

The problem is in this line

image

### Does the bug relate to non-standard syntax?

No

### Proposal to fix the bug

Works correctly with exactly 8.3.11 version of postcss. 
I compared the code in `warning.js` between these versions of postcss (8.3.11 and 8.4.4), they changed the method name. :(

Proposal: change dependencies of stylelint to use exactly 8.3.11 version.

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

Closes #5766

> Is there anything in the PR that needs further explanation?

This PR adds a hack to a situation where there are different PostCSS versions in a dependency tree like a reproduction described on <https://github.com/stylelint/stylelint/issues/5766#issuecomment-1200483928>.

[PostCSS 8.4.0](https://github.com/postcss/postcss/releases/tag/8.4.0) has added the [`Node#rangeBy`](https://postcss.org/api/#node-rangeby) method, while PostCSS 8.3.x or lower doesn't have the method. In the situation above, a parser like `postcss-less` may create a `Node` by an old PostCSS version like 8.3.6. Because the parser's peer dependency version on PostCSS may not match the PostCSS version that Stylelint requires.

* [`postcss-less@6.0.0` requires `postcss@^8.3.5`](https://github.com/shellscape/postcss-less/blob/v6.0.0/package.json#L49-L51) as a peer dependency
* [`stylelint@14.9.1` requires `postcss@^8.4.14`](https://github.com/stylelint/stylelint/blob/14.9.1/package.json#L136) as a normal dependency

Note: If anyone is concerned about adding such a hack, please let me know.

### CODE REVIEW

File: lib/utils/report.js [hunk 1]
```diff
@@ -28,11 +30,9 @@ module.exports = function report(problem) {
 		return;
 	}
 
-	const { start } = (node && node.rangeBy({ index, endIndex })) || {};
-
 	// If a line is not passed, use the node.rangeBy method to get the
 	// line number that the complaint pertains to
-	const startLine = line || (start && start.line);
+	const startLine = line || getStartLine(node, index, endIndex);
```
Comment (ybiquitous) [inline lib/utils/report.js:35]: [note] Call the `rangeBy` method lazily for performance.

File: lib/utils/report.js [hunk 2]
```diff
@@ -109,3 +109,23 @@ module.exports = function report(problem) {
...
+function getStartLine(node, index, endIndex) {
+	if (node === undefined) return undefined;
+
+	// HACK: The `rangeBy` method has been added since PostCSS 8.4.0,
+	//       while the `node` may be produced by PostCSS 8.3.x or lower
+	//       that doesn't have the method.
+	//       See https://github.com/stylelint/stylelint/issues/5766
+	if (node.rangeBy === undefined) {
+		node.rangeBy = postcss.Node.prototype.rangeBy.bind(node);
+	}
```
Comment (ybiquitous) [inline lib/utils/report.js:128]: [note] The implementation of `rangeBy` is here:

https://github.com/postcss/postcss/blob/8.4.14/lib/node.js#L260

This access to `postcss.Node.prototype` may be flaky because of a dependency on the internal implementation of PostCSS.

File: lib/utils/report.js [hunk 3]
```diff
@@ -109,3 +109,23 @@ module.exports = function report(problem) {
...
+ * @returns {number | undefined}
+ */
+function getStartLine(node, index, endIndex) {
+	if (node === undefined) return undefined;
+
+	// HACK: The `rangeBy` method has been added since PostCSS 8.4.0,
+	//       while the `node` may be produced by PostCSS 8.3.x or lower
+	//       that doesn't have the method.
+	//       See https://github.com/stylelint/stylelint/issues/5766
+	if (node.rangeBy === undefined) {
```
Comment (JounQin) [inline lib/utils/report.js:126]: We can add a warning for the user here?

**Review by JounQin — CHANGES_REQUESTED** [review]

File: lib/utils/report.js (hunk 3 above)
Comment (JounQin) [reply lib/utils/report.js:126]:
```suggestion
	if (typeof node.rangeBy !== 'function') {
```

**Review by JounQin — CHANGES_REQUESTED** [review]

File: lib/utils/report.js (hunk 3 above)
Comment (ybiquitous) [reply lib/utils/report.js]: > We can add a warning for the user here?

Nice idea. Changed via 3745154a8. 👍🏼

File: lib/utils/report.js [hunk 4]
```diff
@@ -109,3 +109,26 @@ module.exports = function report(problem) {
...
 };
+
+/**
+ * @param {import('postcss').Node | undefined} node
+ * @param {number | undefined} index
+ * @param {number | undefined} endIndex
+ * @returns {number | undefined}
+ */
+function getStartLine(node, index, endIndex) {
+	if (node === undefined) return undefined;
```
Comment (JounQin) [inline lib/utils/report.js:120]:
```suggestion
	if (!node) return;
```

Maybe a person taste here, or do we have a lint rule to enforce a consistent style?

File: lib/utils/report.js [hunk 5]
```diff
@@ -109,3 +109,26 @@ module.exports = function report(problem) {
...
+
+	// HACK: The `rangeBy` method has been added since PostCSS 8.4.0,
+	//       while the `node` may be produced by PostCSS 8.3.x or lower
+	//       that doesn't have the method.
+	//       See https://github.com/stylelint/stylelint/issues/5766
+	if (typeof node.rangeBy !== 'function') {
+		console.warn(
```
Comment (JounQin) [inline lib/utils/report.js:127]: We can link #5766 as reference at the same time?

And we can check whether it has been warned to ensure it's not noise.

File: lib/utils/report.js [hunk 6]
```diff
@@ -109,3 +109,26 @@ module.exports = function report(problem) {
...
+			'It appears different PostCSS versions are used in your dependency tree. Please consider updating PostCSS to use one version.',
+		);
+		node.rangeBy = postcss.Node.prototype.rangeBy.bind(node);
```
[the remark this answers is not in the document]
Comment (ybiquitous) [reply lib/utils/report.js:130]: It may work without `bind` now, but I've added it just in case. Because it's hard to predict how `rangeBy` is and will be used inside PostCSS.

Or, is there some disadvantage to adding `bind`?

**Review by JounQin — CHANGES_REQUESTED** [review]

File: lib/utils/report.js (hunk 4 above)
Comment (ybiquitous) [reply lib/utils/report.js]: I have no strong opinion about this style. 😅

File: lib/utils/report.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (JounQin) [reply lib/utils/report.js:130]: The prototype itself does not bind, so we don't need to do that neither.

File: lib/utils/report.js (hunk 5 above)
Comment (ybiquitous) [reply lib/utils/report.js]: Make sense. Changed via 95a1ee6de. 👍🏼

File: lib/utils/report.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (ybiquitous) [reply lib/utils/report.js]: I see. Remove via 02a9c7518. 👍🏼

**Review by JounQin — APPROVED** [review]

**Comment by JounQin** [comment]
Awesome work!

File: lib/utils/report.js [hunk 7]
```diff
@@ -109,3 +109,32 @@ module.exports = function report(problem) {
...
+	//       See https://github.com/stylelint/stylelint/issues/5766
+	if (typeof node.rangeBy !== 'function') {
+		if (!warningShown) {
+			console.warn(
+				'It appears different PostCSS versions are used in your dependency tree. Please consider updating PostCSS to use one version. See https://github.com/stylelint/stylelint/issues/5766 for details.',
+			);
+			warningShown = true;
+		}
+
+		node.rangeBy = postcss.Node.prototype.rangeBy;
```
Comment (Mouvedia) [inline lib/utils/report.js:136]: If we ever drop Node.js 12, we could use a dynamic import in the `if`.

Comment (JounQin) [reply lib/utils/report.js:136]: We don't need this PR if https://github.com/stylelint/stylelint/issues/5766#issuecomment-1207260007 works.
