### ISSUE TITLE
Release 15.1.0

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#6647]
- [x] stylelint release
- [x] ~stylelint-config-recommended update/release~ needless
- [x] ~stylelint-config-standard update/release~ needless
- [x] stylelint-demo update
- [x] stylelint.io update
- [x] tweet

We've got a few patches and documentation fixes to go out. I'm away this weekend, but if anyone else has time to do a release, please go ahead.

**Comment by AndyOGo** [comment]
I face that type error again after upgrading to v15

>    TypeError: node.rangeBy is not a function
    at Object.report (/stylelint-declaration-strict-value/node_modules/stylelint/lib/utils/report.js:35:34)

**Comment by jeddy3** [comment]
@AndyOGo Please [open a new issue](https://github.com/stylelint/stylelint/issues/new?assignees=&labels=&template=REPORT_A_BUG.yml) with a reproducible example so that we can best help you.

**Comment by ybiquitous** [comment]
Thanks for opening the issue. I'll do it this weekend if I can have time.

**Comment by ybiquitous** [comment]
We've merged a new feature (#6580), so the next version should be `15.1.0`.
See the [working changelog](https://github.com/stylelint/stylelint/pull/6639/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed).

**Comment by AndyOGo** [comment]
@jeddy3 
Sorry if that is off topic.

I double checked I get postcss through styelint and it is the latest of `8.4.21`.

```sh
npm ls postcss
└─┬ stylelint@15.0.0
  ├─┬ @csstools/selector-specificity@2.1.1
  │ └── postcss@8.4.21 deduped
  ├─┬ postcss-safe-parser@6.0.0
  │ └── postcss@8.4.21 deduped
  └── postcss@8.4.21
```

FYI:
That is my PR to upgrade my plugin to `v15`
https://github.com/AndyOGo/stylelint-declaration-strict-value/pull/310

**Comment by ybiquitous** [comment]
I'll start releasing the new version now.

**Comment by ybiquitous** [comment]
Done! 🎉 

Thanks a lot for your contribution, everyone!
